apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AutoserviceAdmin111//cd.git'
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default1
